[package]
name = "block"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
item = { path = "../item" }
twox-hash = "1.6.3"
phf = { version = "0.11", features = ["macros"] }
