// This file is generated by build.rs
use block::SimpleBlock;

pub struct RegisterBlock {
    pub new: fn(SimpleBlock) -> SimpleBlock,
    pub load: fn(SimpleBlock) -> SimpleBlock,
    pub tags: &'static quickphf::PhfMap<&'static str, &'static str>,
    pub name: &'static str,
}

pub use crate::blocks::AirBlock;
pub use crate::blocks::StoneBlock;
pub use crate::blocks::DirtBlock;
pub const AIR_BLOCK_ID: u16 = 0;
pub static AIR_BLOCK_TAGS: &quickphf::PhfMap<&'static str, &'static str> = &::quickphf::PhfMap::new(
    4294967296,
    &[0, 0, 0, 0],
    &[("can_collide", "false"), ("can_render", "false")],
    &[0]
);

pub const STONE_BLOCK_ID: u16 = 1;
pub static STONE_BLOCK_TAGS: &quickphf::PhfMap<&'static str, &'static str> = &::quickphf::PhfMap::new(
    0,
    &[0],
    &[],
    &[0]
);

pub const DIRT_BLOCK_ID: u16 = 2;
pub static DIRT_BLOCK_TAGS: &quickphf::PhfMap<&'static str, &'static str> = &::quickphf::PhfMap::new(
    0,
    &[0],
    &[],
    &[0]
);


pub static REGISTER_BLOCK: &[RegisterBlock] = &[
    RegisterBlock {new: AirBlock::new, load: AirBlock::load, tags: AIR_BLOCK_TAGS, name: AirBlock::NAME},
    RegisterBlock {new: StoneBlock::new, load: StoneBlock::load, tags: STONE_BLOCK_TAGS, name: StoneBlock::NAME},
    RegisterBlock {new: DirtBlock::new, load: DirtBlock::load, tags: DIRT_BLOCK_TAGS, name: DirtBlock::NAME},
];

