use block::SimpleBlock;
use item::SimpleItem;

/// automatically generated by macro_reg
/// this function is called when the game is ticking the block, item, entity, etc...
pub fn tick_block(_block: &mut SimpleBlock) {
}

/// automatically generated by macro_reg
/// this function is called when the game is ticking the block, item, entity, etc...
pub fn tick_item(_item: &mut SimpleItem) {
}

/// automatically generated by macro_reg
/// this function is called when the game is loading the block, item, entity, etc...
pub fn load_block(block: SimpleBlock) -> SimpleBlock {
    block
}

/// automatically generated by macro_reg
/// this function is called when the game is creating the block, item, entity, etc...
pub fn load_item(item: SimpleItem) -> SimpleItem {
    item
}

/// automatically generated by macro_reg
/// this function is called when the game is loading the block, item, entity, etc...
pub fn new_block(block: SimpleBlock) -> SimpleBlock {
    block
}

/// automatically generated by macro_reg
/// this function is called when the game is creating the block, item, entity, etc...
pub fn new_item(item: SimpleItem) -> SimpleItem {
    item
}