// This file is generated by build.rs
use block::Block;
use block::SimpleBlock;

pub use core::blocks::AirBlock;
pub use core::blocks::StoneBlock;
pub use core::blocks::DirtBlock;

pub static REGISTER_BLOCK: &[fn(Block) -> SimpleBlock] = &[
    AirBlock::new,		// 0
    StoneBlock::new,	// 1
    DirtBlock::new,		// 2
];
