// This file is generated by build.rs
use item::SimpleItem;

pub struct RegisterItem {
        pub new: fn(SimpleItem) -> SimpleItem,
        pub load: fn(SimpleItem) -> SimpleItem,
        pub tags: &'static quickphf::PhfMap<&'static str, &'static str>,
        pub name: &'static str,
    }


pub static REGISTER_ITEM: &[RegisterItem] = &[
];

