[package]
name = "item"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twox-hash = "*"
quickphf = "*"
serde_json = { version = "*", features = ["derive"] }